# Generated by Django 3.1.3 on 2021-04-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='p_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
