# Generated by Django 3.1.3 on 2021-04-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_patient_p_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_date', models.DateTimeField(auto_now=True)),
                ('p_company', models.CharField(max_length=30)),
                ('p_number', models.IntegerField()),
                ('p_alt_number', models.IntegerField()),
                ('p_locality', models.CharField(max_length=30)),
                ('p_city', models.CharField(max_length=30)),
                ('p_state', models.CharField(max_length=30)),
                ('p_remark', models.CharField(max_length=30)),
            ],
        ),
    ]
