# Generated by Django 3.1.3 on 2021-04-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_oxygen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen',
            name='p_alt_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='p_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
