# Generated by Django 3.1.3 on 2021-04-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210425_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plasma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
                ('p_date', models.DateTimeField(auto_now=True)),
                ('p_age', models.IntegerField(max_length=3)),
                ('p_blood', models.CharField(max_length=5)),
                ('p_number', models.IntegerField(max_length=10)),
                ('p_alt_number', models.IntegerField(max_length=10)),
                ('p_locality', models.CharField(max_length=30)),
                ('p_city', models.CharField(max_length=30)),
                ('p_state', models.CharField(max_length=30)),
                ('p_remark', models.CharField(max_length=30)),
            ],
        ),
    ]
