# Generated by Django 3.1.3 on 2021-05-23 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_plasma'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygen',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='p_alt_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='p_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_alt_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='p_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='p_alt_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='p_number',
            field=models.CharField(max_length=30),
        ),
    ]
