# Generated by Django 3.1.3 on 2021-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_oxygen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasma',
            name='p_blood',
            field=models.CharField(max_length=30),
        ),
    ]
